version: 2.1

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache
    key: deps-cache-{{ checksum "package.json" }}

  - &save-deps-cache
    key: deps-cache-{{ checksum "package.json" }}
    paths:
      - ~/project/node_modules

commands:
  setup:
    description: "runs npm install and setups up module cache"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - checkout
      - restore_cache: *restore-deps-cache
      - run: npm install
      - save_cache: *save-deps-cache
  test:
    description: "runs npm install and setups up module cache"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - setup
      - run: npm install codecov
      - run: npm test
      - run: ./node_modules/.bin/codecov
